### ISSUE TITLE
Descrizioni tagliate

### ISSUE THREAD

**Issue by DisGabriele** [Mario21145/PokedexApp#7]
La maggior parte delle descrizioni sono tagliate e si vedono solo in parte (di solito viene tagliata la parte iniziale e/o finale
![Immagine 2023-12-06 103133](https://github.com/Mario21145/PokedexApp/assets/144739624/2e498884-74fb-40f6-adfb-c596097a1e89)
![Immagine 2023-12-06 103159](https://github.com/Mario21145/PokedexApp/assets/144739624/fd9aaa97-feef-466b-bb91-4fda8efa8634)
)

**Comment by DisGabriele** [comment]
Una soluzione potrebbe essere fare in modo che possa scrollare

**Comment by Mario21145** [comment]
### **_Issue resolved by eliminating the icon of the description_**
