### ISSUE TITLE
Search incomplete

### ISSUE THREAD

**Issue by DisGabriele** [Mario21145/PokedexApp#9]
the search feature gives only one pokemon even when it could have give more (ex: if a search for "cro", it gives me "heracross" , but it could have been "crobat")

![image](https://github.com/Mario21145/PokedexApp/assets/144739624/29f005ea-7110-4874-9a80-d6947e005348)

**Comment by DisGabriele** [comment]
a solution could be that it searches considering the uppercase letters too, infact, when i search a pokemon without making the first letter uppercase, it returns nothing

**Comment by Mario21145** [comment]
Issue completed , resolved this problem
